### ISSUE TITLE
Failing on remote instance

### ISSUE THREAD

**Issue by sascharo** [codeitlikemiley/cargo-runner#20]
I can't get Cargo Runner to work when SSH'ed into a remote instance. Running `cargo run` and `cargo run --package test01 --bin test01` in the VS Code terminal works fine, but executing Cargo Runner results in an error.

```
 *  Executing task: cargo run --package test01 --bin test01 

/bin/bash: line 1: cargo: command not found

 *  The terminal process "/bin/bash '-c', 'cargo run --package test01 --bin test01'" failed to launch (exit code: 127). 
```

Any idea what the reason could be?

**Comment by codeitlikemiley** [comment]
the cargo instance on your terminal might be your local cargo installation....

since that is working as you have mention when you run command cargo on terminal it works.

The issue might be your ssh env dont really have cargo installed.


okay heres what you need to do 

type 

```sh
which cargo
```

that would output the path to cargo , it if is already installed , if not you need to installed it using rustup please check rustlang.org



if you do have some output on  the terminal for the cargo path,
what you need to do is add it on your ~/.bashrc or ~/.zshrc 

to be sure you can check what shell you are on using 

```sh
echo $0
```

that would either outpush sh, bash or zsh

you need to edit the file 


since you already ssh and the feedback says no cargo command

the issue is clearly that cargo command is not available on the ENV

you need to modify you ~/.bash_profile  or ~/.bashrc if your using bash
if zsh you need to configure ~/.zshrc or ~/zsh_profile

```
export CARGO_HOME="$HOME/.cargo"
[ -f "$HOME/.cargo/env" ] && source $HOME/.cargo/env
export CARGO_NET_GIT_FETCH_WITH_CLI=true
```

Let me know if this fix your issue.

**Comment by codeitlikemiley** [comment]
Ive tested on codespace using cargo runner

it works just fine...

codespace behaves like ssh as the client is on your local machine and the server is on github codespace

let me know if the solution i mentioned works for you, 

but as far as i can test at the moment , with a quick spin on codespace , i can run cargo runner with no issue.

<img width="1512" alt="Screenshot 2024-08-22 at 7 18 30 AM" src="https://github.com/user-attachments/assets/c891341f-e1a3-444b-af0e-9cd149323342">

**Comment by codeitlikemiley** [comment]
You should have extra configuration on vscode just for the remote / ssh container

see mine
<img width="1512" alt="Screenshot 2024-08-22 at 7 23 05 AM" src="https://github.com/user-attachments/assets/ee2b15fd-e249-452f-941f-eca02c4b8553">

**Comment by sascharo** [comment]
`which cargo`
```
/home/ubuntu/.cargo/bin/cargo
```

`echo $0`
```
/bin/bash
```
> You should have extra configuration on vscode just for the remote / ssh container
> 
> see mine <img alt="Screenshot 2024-08-22 at 7 23 05 AM" width="1512" src="https://private-user-images.githubusercontent.com/28816690/360160738-ee2b15fd-e249-452f-941f-eca02c4b8553.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjM4OTksIm5iZiI6MTcyNDMyMzU5OSwicGF0aCI6Ii8yODgxNjY5MC8zNjAxNjA3MzgtZWUyYjE1ZmQtZTI0OS00NTJmLTk0MWYtZWNhMDJjNGI4NTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwNDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MjFkMTZjZTFkM2JhNTgyOGZlNWI4MDYzNmZlYWRmZGIyYjNlNWI4NWZlZTc5YjZjOTJmZGYwNzk2NDkyM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6fWY_NeVB5z1s7_FDQdGusKnHKFT7N2U1w59gheX0pM">

Yeah, that was already installed on the remote box.

That being said, I didn't change anything and just stopped the instance last night and started it again just now. Well, it works out of the box now. I'm using an Oracle Ampere VM instance.

Thanks for looking into this!

Yesterday, I thought the issue might be related to this one: 
https://github.com/rust-lang/rust-analyzer/issues/14381 and https://github.com/microsoft/vscode-remote-release/issues/8312
